### ISSUE TITLE
Support for Neo4j 4.0.x

### ISSUE THREAD

**Issue by jkcdarunday** [graphaware/neo4j-framework#109]
Hi,
Neo4j 4.0 was released early last month with support for sharding and multiple databases which makes it able to scale horizontally more than before. Drivers and other libraries like Graphaware's Spring Data Neo4j and Neo4j OGM are already compatible with it except for this framework which is the last thing blocking our upgrade.

Are there plans to support the next version for this framework and, if yes, is there perhaps a timeline for this?

Thank you.

**Comment by foobargeez** [comment]
Hello,
I am blocked on the latest version of neo4j-framework and timetree plugin to work with neo4j 4.x.  Are there plans to be compatible with 4.x?  If so, can you please post a tentative timeline so I can plan my upgrade accordingly?  Thanks!

**Comment by johanwasserman** [comment]
bump

**Comment by J-Krush** [comment]
Is there a reason 4.x isn't supported yet?

**Comment by J-Krush** [comment]
@jkcdarunday or @foobargeez Did you find any workarounds? I'm probably not going to use this framework because of the lack of support.

**Comment by foobargeez** [comment]
> @jkcdarunday or @foobargeez Did you find any workarounds? I'm probably not going to use this framework because of the lack of support.

Nope :-( I dropped this when I upgraded to Neo4j v4.  Timetree blocked my upgrade to Neo4j v4 but I was able to temporarily work around in my code.

**Comment by J-Krush** [comment]
@foobargeez Bummerrrrr.. thanks for the response, though!

**Comment by ikwattro** [comment]
There is support for 4.x -> products.graphaware.com
