### ISSUE TITLE
GraphUnit.areSameGraph(GraphDatabaseService database, String sameGraphCypher) should be static

### ISSUE THREAD

**Issue by mcclown** [graphaware/neo4j-framework#115]
GraphUnit has a private constructor, so this method can never be called.

**Comment by ikwattro** [comment]
Method is public, the private constructor is on purpose.

**Comment by mcclown** [comment]
That's missing the point, you didn't read the title. 

GraphUnit.areSameGraph(GraphDatabaseService database, String sameGraphCypher) is the only non-static method on this class. You can't create an instance of this class, so therefore this method can't be called. This method should be static.

**Comment by bachmanm** [comment]
Stephen, do you need a build for 4.1.x?

**Comment by mcclown** [comment]
@bachmanm No, I'm fine. I had a look at the source and just used GraphUnit.areSameGraph(GraphDatabaseService database, String sameGraphCypher, InclusionPolicies inclusionPolicies) instead with InclusionPolicies.all().
