### ISSUE TITLE
SingleThreadedWriter logging uses seconds rather than ms

### ISSUE THREAD

**Issue by jbkielis** [graphaware/neo4j-framework#20]
I've attached a screenshot with the offending code.  I think the TimeUnit just needs to switch to MS.

![image](https://cloud.githubusercontent.com/assets/8429873/8065670/f630048e-0eb0-11e5-9133-d830b89203a9.png)

**Comment by bachmanm** [comment]
Good catch! :+1: Will fix in the next release.

**Comment by bachmanm** [comment]
fix will be released with the next version of the framework
