### ISSUE TITLE
Debian jessie, graphaware  plugins are not working

### ISSUE THREAD

**Issue by gokulreddy07** [graphaware/neo4j-framework#25]
I don't know what went wrong with your plugins, tried several times installing.

this is my configuration and copied required framework jar and plugins jar.

com.graphaware.runtime.enabled=true

#******** Graphaware UUID ***** #

#*UIDM becomes the module ID:
com.graphaware.module.UIDM.1=com.graphaware.module.uuid.UuidBootstrapper

#*optional, default is uuid:
com.graphaware.module.UIDM.uuidProperty=uuid

#*optional, default is all nodes:
#*com.graphaware.module.UIDM.node=hasLabel('Label1') || hasLabel('Label2')

#*optional, default is uuidIndex
com.graphaware.module.UIDM.uuidIndex=uuidIndex

#****** Graphaware Timetree plugin******##

#* A Runtime module that takes care of attaching the events like this (TT is the ID of the module)
com.graphaware.module.TT.2=com.graphaware.module.timetree.module.TimeTreeModuleBootstrapper

#* Nodes which represent events and should be attached automatically have to be defined
com.graphaware.module.TT.event=hasLabel('Product')

#* Optionally, a property on the event nodes that represents the the time (long) at which the event took place must be specified (defaults to "timestamp")
com.graphaware.module.TT.timestamp=time

#* Optionally, a property on the event nodes that represents the node ID (long) of the root node for the tree, to which the event should be attached (defaults to "timeTreeRootId")
com.graphaware.module.TT.customTimeTreeRootProperty=rootId

#* Optionally, a resolution can be specified (defaults to DAY)
com.graphaware.module.TT.resolution=Minute

#* Optionally, a time zone can be specified (defaults to UTC)
#*com.graphaware.module.TT.timezone=UTC

#* Optionally, a relationship type with which the events will be attached to the tree can be specified (defaults to AT_TIME)
com.graphaware.module.TT.relationship=CREATED_ON

#* autoAttach must be set to true
com.graphaware.module.TT.autoAttach=true

**Comment by bachmanm** [comment]
What version if neo4j and graphaware? What's not working? Could you please provide console.log from /data/log after you start the db? Thanks

**Comment by gokulreddy07** [comment]
I'm using neo4j 2.2.3 and graphaware framework is 2.2.2.32 server. i'm trying to create timetree and uuid using graphaware timetree and uuid plugins along with graphaware framework server i tried it but its not creating

Here is my console.log

"2015-07-28 06:42:40.153+0000 INFO  [API] Setting startup timeout to: 120000ms based on 120000
2015-07-28 06:42:44.484+0000 INFO  [API] Successfully started database
2015-07-28 06:42:44.556+0000 INFO  [API] Starting HTTP on port :7474 with 4 threads available
2015-07-28 06:42:44.707+0000 INFO  [API] Enabling HTTPS on port :7473
2015-07-28 06:42:44.708+0000 INFO  [API] No SSL certificate found, generating a self-signed certificate..
12:12:45.131 [main] INFO  org.eclipse.jetty.util.log - Logging initialized @6613ms
2015-07-28 06:42:45.184+0000 INFO  [API] Mounting static content at [/webadmin] from [webadmin-html]
2015-07-28 06:42:45.231+0000 INFO  [API] Mounting static content at [/browser] from [browser]
12:12:45.235 [main] INFO  org.eclipse.jetty.server.Server - jetty-9.2.4.v20141103
12:12:45.255 [main] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.s.h.MovedContextHandler@6f9a11a3{/,null,AVAILABLE}
12:12:45.332 [main] INFO  o.e.j.w.StandardDescriptorProcessor - NO JSP Support for /webadmin, did not find org.apache.jasper.servlet.JspServlet
12:12:45.346 [main] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.w.WebAppContext@19f9e774{/webadmin,jar:file:/usr/share/neo4j/system/lib/neo4j-server-2.2.3-static-web.jar!/webadmin-html,AVAILABLE}
12:12:45.894 [main] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@30609c8e{/db/manage,null,AVAILABLE}
12:12:46.196 [main] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@557ad6ae{/db/data,null,AVAILABLE}
12:12:46.213 [main] INFO  o.e.j.w.StandardDescriptorProcessor - NO JSP Support for /browser, did not find org.apache.jasper.servlet.JspServlet
12:12:46.214 [main] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.w.WebAppContext@67673129{/browser,jar:file:/usr/share/neo4j/system/lib/neo4j-browser-2.2.3.jar!/browser,AVAILABLE}
12:12:46.317 [main] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@5ea0a29b{/,null,AVAILABLE}
12:12:46.384 [main] INFO  o.e.jetty.server.ServerConnector - Started ServerConnector@27aa2d2d{HTTP/1.1}{localhost:7474}
12:12:46.527 [main] INFO  o.e.jetty.server.ServerConnector - Started ServerConnector@726fca56{SSL-HTTP/1.1}{localhost:7473}
12:12:46.528 [main] INFO  org.eclipse.jetty.server.Server - Started @8015ms
2015-07-28 06:42:46.528+0000 INFO  [API] Server started on: http://localhost:7474/
2015-07-28 06:42:46.529+0000 INFO  [API] Remote interface ready and available at [http://localhost:7474/]
2015-07-28 07:28:32.689+0000 INFO  [API] Neo4j Server shutdown initiated by request
12:58:32.700 [Thread-13] INFO  o.e.jetty.server.ServerConnector - Stopped ServerConnector@27aa2d2d{HTTP/1.1}{localhost:7474}
12:58:32.700 [Thread-13] INFO  o.e.jetty.server.ServerConnector - Stopped ServerConnector@726fca56{SSL-HTTP/1.1}{localhost:7473}
12:58:32.702 [Thread-13] INFO  o.e.j.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@5ea0a29b{/,null,UNAVAILABLE}
12:58:32.704 [Thread-13] INFO  o.e.j.server.handler.ContextHandler - Stopped o.e.j.w.WebAppContext@67673129{/browser,jar:file:/usr/share/neo4j/system/lib/neo4j-browser-2.2.3.jar!/browser,UNAVAILABLE}
12:58:32.711 [Thread-13] INFO  o.e.j.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@557ad6ae{/db/data,null,UNAVAILABLE}
12:58:32.712 [Thread-13] INFO  o.e.j.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@30609c8e{/db/manage,null,UNAVAILABLE}
12:58:32.713 [Thread-13] INFO  o.e.j.server.handler.ContextHandler - Stopped o.e.j.w.WebAppContext@19f9e774{/webadmin,jar:file:/usr/share/neo4j/system/lib/neo4j-server-2.2.3-static-web.jar!/webadmin-html,UNAVAILABLE}
12:58:32.714 [Thread-13] INFO  o.e.j.server.handler.ContextHandler - Stopped o.e.j.s.h.MovedContextHandler@6f9a11a3{/,null,UNAVAILABLE}
2015-07-28 07:28:33.128+0000 INFO  [API] Successfully shutdown Neo4j Server.
"

**Comment by bachmanm** [comment]
Please use neo4j 2.2.2, there's a bug in 2.2.3 that affects the framework (https://github.com/neo4j/neo4j/issues/4910). That's why we haven't released a version of the framework compatible with 2.2.3
