### ISSUE TITLE
Unable to download plugins

### ISSUE THREAD

**Issue by gokulreddy07** [graphaware/neo4j-framework#29]
Hi guy's unable to download any of graphaware plugins its showing 404 error.

**Comment by MicTech** [comment]
We really apologize for this inconvenience. It's just temporarily disabled due to a site maintenance.

You can download them from the GitHub. Here is the page for the GraphAware Framework: https://github.com/graphaware/neo4j-framework/releases

**Comment by bachmanm** [comment]
Thanks @MicTech for picking this up. The products are also going to be available on http://products.graphawre.com, but the website (though still being changed actively) should now be fixed.
