### ISSUE TITLE
Does this package provide hooks to allow addition of custom jmx filters?

### ISSUE THREAD

**Issue by jbkielis** [graphaware/neo4j-framework#31]
I'd like to add a javax.servlet.Filter in order to do GZIP compression.  Does this library allow us to hook into jetty server setup in order to add this?

Thanks.

**Comment by bachmanm** [comment]
Yes, but not without coding. We already do this for a Filter we need - have a look here: https://github.com/graphaware/neo4j-framework/blob/master/server/server-common/src/main/java/com/graphaware/server/web/GraphAwareJetty9WebServer.java#L219

Without changes to the Framework, you'd have to extend `GraphAwareJetty9WebServer` and override the `setDefaultInjectables` method, then override `GraphAwareCommunityNeoServer` or `GraphAwareEnterpriseNeoServer`to instantiate your Web Server, and finally override `GraphAwareCommunityBootstrapper` or `GraphAwareEnterpriseBootstrapper` to instantiate your Neo Server.

We could build a mechanism for you to hook Filters up without coding as paid consultancy. Alternatively create a feature request and we'll look at it when we can. Or even better, if you manage, please issue a pull request.

Thank!
