### ISSUE TITLE
Missing artifact com.eaio.uuid:uuid:jar:3.4

### ISSUE THREAD

**Issue by magaton** [graphaware/neo4j-framework#34]
There is no 3.4 version in central maven repo.

**Comment by bachmanm** [comment]
I know :( But that's why there's a separate repo defined in pom.xml. Is this a problem? Thanks!

**Comment by magaton** [comment]
I agree that this should be a separate repo, but I had to specify it in neo4j-importer (and any other project that is using graphaware module parent), otherwise it won't build.

**Comment by moshebeeri** [comment]
Same thing here, but worse. since I'm using SBT.
trying to use reco via Scala, any work around?

**Comment by bachmanm** [comment]
Could you guys try with latest release 2.3.1.36? It should be fixed as I downgraded the dependency to 3.2, which is present in Central...

**Comment by moshebeeri** [comment]
Thanks but I get 500 server error when trying to download latest, not even 404 :-(

**Comment by bachmanm** [comment]
try now
