### ISSUE TITLE
Installation fails 'The ResourceConfig instance does not contain any root resource classes'

### ISSUE THREAD

**Issue by Danielss89** [graphaware/neo4j-framework#39]
Hi
I'm trying to install TimeTree(and graphaware framework).
I've copied the timetree and framework .jar files into plugins folder added ` org.neo4j.server.thirdparty_jaxrs_classes=com.graphaware.server=/graphaware` to the end of `/etc/neo4j/neo4j-server.properties` but i'm getting an error when restarting neo4j:

```
The ResourceConfig instance does not contain any root resource classes.
```

Full error log here: https://gist.github.com/Danielss89/01bb24ccaae0f23a988a

**Comment by ikwattro** [comment]
Hi,

Can you provide the neo4j version, framework and timetree versions you are using.

Thanks !

**Comment by Danielss89** [comment]
graphaware-server-community-all-2.3.1.36
graphaware-timetree-2.3.1.36.24
graphaware-uuid-2.3.1.36.7

Neo4j: 2.3.1 Community

**Comment by bachmanm** [comment]
This is weird... what's the output of `ls -alh` of your `plugins` directory? The error looks like you do not have the framework .jar in plugins.

**Comment by Danielss89** [comment]
```
[07:13 PM]-[root@frievent]-[/var/lib/neo4j/plugins] 
# ls -alh
total 14M
drwxr-xr-x 2 neo4j adm  4.0K Nov 26 21:47 ./
drwxr-xr-x 5 neo4j adm  4.0K Nov 18 10:51 ../
-rw-r--r-- 1 neo4j adm   273 Nov 10 14:15 README.txt
-rw-r----- 1 root  root  13M Nov 26 21:47 graphaware-server-community-all-2.3.1.36.jar
-rw-r----- 1 root  root 628K Nov 26 21:32 graphaware-timetree-2.3.1.36.24.jar
-rw-r----- 1 root  root  14K Nov 26 21:33 graphaware-uuid-2.3.1.36.7.jar
```

**Comment by bachmanm** [comment]
Permissons? :)

**Comment by Danielss89** [comment]
What should the be?

**Comment by bachmanm** [comment]
Try neo4j:adm also for the plugins...

**Comment by bachmanm** [comment]
success?

**Comment by Danielss89** [comment]
yes, just changed the permissions, and now it works! thanks.
