### ISSUE TITLE
Latest version is still 2.3.3 despite README

### ISSUE THREAD

**Issue by dmitriid** [graphaware/neo4j-framework#46]
The README states: 

> GraphAware Neo4j Framework
> Latest Release: 3.0.0.38

The latest available download is 2.3.3.37-3 which breaks Neo4J 3.0.0

**Comment by dmitriid** [comment]
The link to 3.0.0.38 is broken and produces HTTP 500: http://products.graphaware.com/download/framework-server-community/graphaware-server-community-all-3.0.0.38.jar

**Comment by ikwattro** [comment]
Thanks it should be upped now http://products.graphaware.com/download/framework-server-community/latest

**Comment by dmitriid** [comment]
Awesome, thanks!

Quick question: will it work with latest versions of TimeTree?

**Comment by ikwattro** [comment]
TimeTree is not yet upgraded, we're busy on it (there is actually a migration branch). We expect to have our modules compatible with 3.0 during the weekend.

**Comment by dmitriid** [comment]
You're awesome! Thank you!
