### ISSUE TITLE
Error in console.log when runnning the framework neo4j 3.0.1

### ISSUE THREAD

**Issue by royipressburger** [graphaware/neo4j-framework#47]
Hi

Im running the framework with the `uuid module` and i get some warnnins in the `console.log`.
Im not sure it something critical cause all seems to work fine:

`2016-05-10 08:39:32.740+0000 WARN  [o.n.k.i.p.Procedures] Failed to load `org.apache.commons.logging.impl.AvalonLogger` from plugin jar `/var/lib/neo4j/plugins/graphaware-server-enterprise-all-3.0.0.38.jar`: org/apache/avalon/framework/logger/Logger`

This is one example for the warnings, I also get the same warrnings for:

org.springframework.core.type.filter.AspectJTypeFilter
org.springframework.web
org.springframework.http
org.springframework.scripting

and some more..
its this something to worry about?

**Comment by ikwattro** [comment]
Thanks for the report, we'll look into it. Can you confirm you don't have any other plugins than the framework and the uuid module ? Thanks.

**Comment by royipressburger** [comment]
yes no other plugins...

**Comment by bachmanm** [comment]
This is not an issue at all, you can safely ignore the warnings. It is a very minor issue in Neo4j in that it uses a strange mechanism to detect procedures. I think we should report it as such.
