### ISSUE TITLE
Logging in Neo4j 3.0?

### ISSUE THREAD

**Issue by jbkielis** [graphaware/neo4j-framework#49]
How does logging work when creating unmanaged modules in server-mode in Neo4j 3.0?  All the examples seem to use slf4j configured via logback.xml.  However, that doesn't seem to work anymore.

Thanks.

**Comment by bachmanm** [comment]
This will be fixed in the next release which will be compatible with Neo4j 3.0.2. No more logback - it will use Neo4j's own logging mechanism
