### ISSUE TITLE
Data collection not being disabled...

### ISSUE THREAD

**Issue by espiegelberg** [graphaware/neo4j-framework#59]
I have been involved with multiple Neo4j projects and have made use of GraphAware’s neo4j-framework several times; it is incredibly useful and powerful.

Some of the projects have decided to opt out of the framework’s use of Google Analytics for anonymous statistic collection. Despite having followed the instructions in the “Data Collection” section of https://github.com/graphaware/neo4j-framework, when working locally with no network I have noticed that the following error appears in my Neo4j log:
```
…
17:05:03.145 [pool-4-thread-1] WARN c.g.c.p.GoogleAnalyticsStatsCollector - Unable to collect stats
java.net.UnknownHostException: www.google-analytics.com
    at java.net.InetAddress.getAllByName0(InetAddress.java:12380) ~[na:1.8.0_120]
...
```
Having cross-checked the documentation and the code, I believe I have found a discrepancy. While the documentation refers to “com.graphaware.runtime.stats.disabled” (with a trailing “d”), the Neo4jConfigBaseRuntimeConfiguration, on line 89 and 117, and GraphAwareWebContextCreator, on line 34, both make use of “com.graphaware.runtime.stats.disable” (without the trailing “d”). I believe this explains why, despite having taken steps to disable it, I am still seeing the framework attempt to report statistics.

While it is arguably an easier fix to simply update the documentation to match the code, this then requires framework users, who believe they have already disabled the collection, to be aware of the problem, to update to the latest release (once a fix is available), and to then once again update their neo4j.conf. The other approach, of updating the code to match the documentation, would have the benefit of that framework users, who believe they have already disabled the collection, will suddenly have the collection actually disabled when they upgrade to the newest release.

**Comment by bachmanm** [comment]
fixed by supporting both versions
