### ISSUE TITLE
Writing a module that works with Elasticsearch (Lucene package conflict)

### ISSUE THREAD

**Issue by ziadloo** [graphaware/neo4j-framework#65]
I know this is not an issue, but it would be great if you can help figure out how to solve it. I'm trying to write a module like the one you've got [here](https://github.com/graphaware/neo4j-framework/blob/master/examples/friendship-strength-counter-module/pom.xml) which works with Elasticsearch on the side.

The problem I've got is that Neo4j and Elasticsearch both use Lucene but unfortunately very different versions (Neo4j: 5.5.0 and Elasticsearch: 6.1.0). These two versions are incompatible and this makes it impossible to compose such a project. I wonder if you know of a way to do so? And I really can not use older versions of Elasticsearch.

**Comment by bachmanm** [comment]
Have a look at https://github.com/graphaware/neo4j-to-elasticsearch and https://github.com/graphaware/graph-aided-search to see how we're dealing with this in unit tests. In production code, I'm not sure you can have both Neo4j and ES run in the same JVM :/

**Comment by ziadloo** [comment]
Thanks, that's disappointing

**Comment by ikwattro** [comment]
That's java
