### ISSUE TITLE
Neo4j crashes when "com.graphaware.runtime.enabled=true" is added to the neo4j.conf file

### ISSUE THREAD

**Issue by Jennipalli-V-Tejaswini** [graphaware/neo4j-framework#84]
neo4j version 3.3.0.

I am trying to implement an nlp requirement.

According to the instructions here-  https://github.com/graphaware/neo4j-nlp   ,I have added the 4 jars->
/var/lib/neo4j/plugins/graphaware-embedded-all-3.3.0.52-SNAPSHOT.jar
/var/lib/neo4j/plugins/graphaware-nlp-3.3.0.51.2-SNAPSHOT.jar
/var/lib/neo4j/plugins/graphaware-server-community-all-3.3.0.51(1).jar
/var/lib/neo4j/plugins/nlp-opennlp-3.3.0.51.2-SNAPSHOT.jar

I have added these lines to my neo4j.conf

dbms.unmanaged_extension_classes=com.graphaware.server=/graphaware
  com.graphaware.runtime.enabled=true
  com.graphaware.module.NLP.1=com.graphaware.nlp.module.NLPBootstrapper
  dbms.security.procedures.whitelist=ga.nlp.*

The issue is that localhost:7474 doesn't repond when I add the line   "com.graphaware.runtime.enabled=true" to the config file. If this line is commented, neo4j loads in the browser but throws "Failed to invoke procedure ga.nlp.annotate: Caused by: java.lang.IllegalStateException: No GraphAware Runtime is registered with the given database".

I have attached the debug.log which ends with n number of "GC Monitor: Application threads blocked for "

I am working with a system having free RAM of (6GB out of 8GB) before starting neo4j.

[debug.log](https://github.com/graphaware/neo4j-framework/files/1497259/debug.log)

**Comment by ikwattro** [comment]
Can you try to increase the memory for the heap of neo4j : 

```
dbms.memory.heap.initial_size=4096m
dbms.memory.heap.max_size=6192m
```

**Comment by Jennipalli-V-Tejaswini** [comment]
Worked.  Thanks
