### ISSUE TITLE
Can not resolve com.neo4j:neo4j-cypher-slotted-runtime

### ISSUE THREAD

**Issue by noeljackson** [graphaware/neo4j-framework#91]
When building neo4j-framework with maven, it used to work without a problem. After trying to build for Neo4j 3.5 I run into the following issue where I am not authorized to get cypher slotted runtime. Is there something I can do to fix this issue?

```
[INFO] ---------------< com.graphaware.neo4j:framework-parent >----------------
[INFO] Building GraphAware Neo4j Framework 3.5.0.54-SNAPSHOT             [2/24]
[INFO] --------------------------------[ pom ]---------------------------------
Downloading from neo4j-enterprise: https://neo4j.bintray.com/enterprise/com/neo4j/neo4j-cypher-slotted-runtime/3.5.0/neo4j-cypher-slotted-runtime-3.5.0.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for GraphAware Neo4j Framework Parent POM 3.5.0.54-SNAPSHOT:
[INFO] 
[INFO] GraphAware Neo4j Framework Parent POM .............. SUCCESS [  0.878 s]
[INFO] GraphAware Neo4j Framework ......................... FAILURE [  0.956 s]
```
`
[ERROR] Failed to execute goal on project framework-parent: Could not resolve dependencies for project com.graphaware.neo4j:framework-parent:pom:3.5.0.54-SNAPSHOT: Failed to collect dependencies at com.neo4j:neo4j-cypher-slotted-runtime:jar:3.5.0: Failed to read artifact descriptor for com.neo4j:neo4j-cypher-slotted-runtime:jar:3.5.0: Could not transfer artifact com.neo4j:neo4j-cypher-slotted-runtime:pom:3.5.0 from/to neo4j-enterprise (https://neo4j.bintray.com/enterprise): Not authorized -> [Help 1]
`

**Comment by ikwattro** [comment]
Hi @noeljackson 

Following the [shift of Neo4j to an OpenCore licensing model](https://neo4j.com/blog/open-core-licensing-model-neo4j-enterprise-edition/) , the `neo4j-cypher-slotted-runtime` is a `neo4j-enterprise` dependency. You'll need to get the credentials for accessing those. 

What does it mean for the framework ? I believe over time we might have a separate framework repository that relies on the neo4j-enterprise artifacts, however this will require a bit time outside of our day jobs.

The jar itself is published to Maven, are you doing changes to the framework that require you to build it manually ? Generally you can use the framework as a parent-module which will not require you to have access to the neo4j enterprise artifacts.

**Comment by bachmanm** [comment]
All Neo4j enterprise dependencies have now been removed from the Community version of this framework, starting with version 3.5.14.58. Please check it out.
