### ISSUE TITLE
Upgrading to Neo4j 3.5.6 causes server integration tests that load the browser to fail

### ISSUE THREAD

**Issue by luanne** [graphaware/neo4j-framework#96]
```
 public void shouldLoadBrowser() {
        httpClient.get(baseNeoUrl() + "/browser", SC_OK);
    }
```
in 
`GraphAwareIntegrationTestTest`, `NeoServerIntegrationTestTest`, `ServerIntegrationTestTest`

fail against Neo4j 3.5.6 and Neo4j 3.5.7
Last working version is Neo4j 3.5.5

**Comment by bachmanm** [comment]
This is due to an internals change in Neo4j, should be fixed in latest releases
